name: Test and Release
on:
  push:
    branches: [master]

env:
  PYTHON_VERSION: "3.8.5"
  PROJECT_FOLDER: ./rajinipp
  TEST_FOLDER: tests

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Configure poetry & Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry && poetry install

      - name: View poetry version
        run: poetry --version

      - name: Lint with flake8
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ${{env.PROJECT_FOLDER}}
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false

          extra-flake8-options: "--max-line-length 79 --max-complexity 15 --config .flake8"

      - name: Black formatting check
        uses: psf/black@stable
        with:
          options: "--config .black"
          src: ${{env.PROJECT_FOLDER}}
          version: "22.3.0"

      - name: Test with pytest
        run: |
          poetry run python -m pytest -v ${{env.TEST_FOLDER}}

  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Python Semantic Release
        uses: aadhithya/py-semantic-release-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
